### ISSUE TITLE
`no-wrap` not a valid value for `white-space` CSS property

### ISSUE THREAD

**Issue by bartveneman** [lonelyplanet/rizzo#1183]
The `no-wrap` value for the `white-space` property used in `.badge` is not a valid value. Should be `nowrap`. W3C has to figure out when to use hyphens and when not.

Reference: http://www.w3.org/wiki/CSS/Properties/white-space, https://developer.mozilla.org/en-US/docs/Web/CSS/white-space

**Comment by chee** [comment]
ur rite
