### ISSUE TITLE
Autocomplete on Contact us  page isn't accurate

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1474]
The auto-complete list is displaying non-existent titles and old editions.  This doesn't happen with every title. The titles I have noticed are Poland, Germany, Ireland, USA. 

The auto-complete should display only existing titles and only the latest edition of these.  It looks like search engine for LP apps is returning redundant records

**Comment by laserchicken** [comment]
@lemmiestone could you please paste a screenshot? this is my first contact with this app, I'm not sure what you mean

**Comment by lemmiestone** [comment]
@laserchicken I've attached an image.  From my understanding we should only display existing titles and not legacy titles.  Looking at the screenshot it shows 3 guidebooks for Germany.  I am confirming that there are still legacy titles coming up.

![screen shot 2016-03-11 at 8 53 49 am](https://cloud.githubusercontent.com/assets/556150/13705744/c39d5766-e767-11e5-9886-d9949f6db95e.png)

**Comment by lemmiestone** [comment]
I am closing this. Ellie reported that it's working fine now.
