### ISSUE TITLE
No currency symbol for Turkey

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1475]
The currency symbol TL (for Turkish Lira) doesn't appear on http://www.lonelyplanet.com/turkey/essential-information (and links from this page like Telephone) and http://www.lonelyplanet.com/turkey/money-costs

This is fine on chrome on mac but doesn't work on chrome on PC

**Comment by lemmiestone** [comment]
@madmaniak this appears to only be happing in windows 7

**Comment by jcreamer898** [comment]
Wow, surprised by our numbers here... 

![](http://d.pr/i/1jDo5+)

**Comment by laserchicken** [comment]
New turkish lira sign was introduced in 2012 (two years after Widows 7 release). There are some problems with displaying it on Windows 7, Microsoft suggests downloading an update (https://support.microsoft.com/en-us/kb/2739286), I'm not sure why it's not being updated automatically. One solution which comes to my mind is adding some js code, which will detect Windows 7 and replace text symbol with image. What do you think about that? @lemmiestone

**Comment by laserchicken** [comment]
This is how svg based solution looks on Windows7/chrome:
![screen shot 2016-03-31 at 18 46 51](https://cloud.githubusercontent.com/assets/5850443/14183541/1fe55604-f771-11e5-99af-376a0757f3d8.png)
I'm afraid that's the best we can do, ship it? @lemmiestone

**Comment by lemmiestone** [comment]
I think that's fine for those users.  They need to upgrade :)

**Comment by laserchicken** [comment]
@lemmiestone that's fixed now, can be closed
