### ISSUE TITLE
Photos tab not working

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1476]
The photos tab below photos doesn't do anything.  Example- http://www.lonelyplanet.com/europe/tours/history-culture/eastern-europe-croatia-balkans

**Comment by laserchicken** [comment]
@lemmiestone do you mean photos button? I can click either photos or map:
![screen shot 2016-03-10 at 17 44 57](https://cloud.githubusercontent.com/assets/5850443/13676911/02b04f2e-e6e8-11e5-8a69-a16adedf1490.png)
![screen shot 2016-03-10 at 17 45 04](https://cloud.githubusercontent.com/assets/5850443/13676918/0787d332-e6e8-11e5-9093-10f3b5496c74.png)

**Comment by lemmiestone** [comment]
This looks to be resolved I will close it.
