### ISSUE TITLE
Switch from Lever to Recruiter box

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1477]
We are moving from Lever and going back to recruiter box.

Below is link to our account and a link to their API.  All styles will need to stay the same the only difference is that application will be submitted to to RB

https://lonelyplanet.recruiterbox.com/
developers.recruiterbox.com

Our hope is to have this wrapped up this week and we can go live next week.

Let me know if you need anything else.

**Comment by jcreamer898** [comment]
https://jsapi.recruiterbox.com/v1/openings/?client_name=lonelyplanet

**Comment by jcreamer898** [comment]
Done.

**Comment by lemmiestone** [comment]
@jcreamer898 can we take users straight to the application vs making them hit Apply twice?  Right now a user is required to hit apply twice

**Comment by lemmiestone** [comment]
@jcreamer898 I should have reopened this ticket when I made the comment above.  We need to take users directly to the application.

**Comment by lemmiestone** [comment]
@jcreamer898 I'm going to have @amccadams take a look at this

**Comment by lemmiestone** [comment]
@amccadams Jonathan did the initial work on this but we need to remove our landing page and go directly to the RB job application

**Comment by lemmiestone** [comment]
This issue was moved to lonelyplanet/jobs#7
