### ISSUE TITLE
Update Work Experience page

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1479]
I don't know the details about this but it seems like you did.  We need to update http://www.lonelyplanet.com/careers/#work-experience

**Comment by lemmiestone** [comment]
@jcreamer898 do you think you could knock this out tomorrow?

**Comment by jcreamer898** [comment]
They never actually told me what to do haha. 

Sent from Outlook Mobile. Yes, it works with gmail.




On Thu, Mar 3, 2016 at 1:43 PM -0800, "lemmiestone" <notifications@github.com> wrote:












@jcreamer898 do you think you could knock this out tomorrow?

**Comment by lemmiestone** [comment]
@jcreamer898  from what I understand Kathy created a job opening for the work experience program.  That application should appear on this page.

**Comment by lemmiestone** [comment]
I am still waiting to get clarification from Kathy on exactly what she wants.

**Comment by lemmiestone** [comment]
Based on Kathy's email I still think it makes the most sense to just show the application when a user clicks on Work Experience, otherwise they will read the description click apply and then have to do it all over again.

**Comment by lemmiestone** [comment]
@jcreamer898 I'm going to have @amccadams take a look at this

**Comment by jcreamer898** [comment]
Feel free to give it a shot Amanda. It can be a little confusing so just hit me up if you have issues.

**Comment by lemmiestone** [comment]
This issue was moved to lonelyplanet/jobs#6
