### ISSUE TITLE
Flights Widget needs to be updated

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1494]
Below are instructions from skyscanner on what we need to do to fix our widget.

The URL structure of Skyscanner Whitelabel V2 is a bit different.

The new format for the parameters is this:
http://flights.lonelyplanet.com/en-GB/flights#/result?originplace=AMS&destinationplace=PARI&outbounddate=2016-03-18&inbounddate=2016-03-24&cabinclass=Economy&adults=1&children=0&infants=0

We are currently using the following:
http://flights.lonelyplanet.com/Flights?&outboundDate=2016-03-14&inboundDate=2016-03-15&originPlace=AMS&destinationPlace=PARI&adults=1&children=0&infants=0&country=GB&currency=GBP&locationSchema=sky&cabinClass=economy&searchcontrols=true

So basically we need to change /Flights to /en-GB/flights and provide the rest of the parameters as a hash (#/result?).

The next thing is to change to lowercase the outboundDate, inboundDate, originPlace, destinationPlace and cabinClass parameter names (outbounddate, inbounddate, originplace, destinationplace, cabinclass)
Also you can drop the searchcontrols and locationSchema parameters, they are no longer needed.

However, if we want to supply the currency, it needs to be as a query parameters:
http://flights.lonelyplanet.com/en-GB/flights?currency=USD&#/result?originplace=AMS&destinationplace=PARI&outbounddate=2016-03-18&inbounddate=2016-03-24&cabinclass=Economy&adults=1&children=0&infants=0
Keep in mind that this url will be rewritten and you won’t see the currency parameter once landed on the page. But it will be saved in the users localStorage until it’s changed.

**Comment by lemmiestone** [comment]
Skyscanner devs looked at the widget and  mentioned that the only change we have to make is in the widget’s _buildUrl method.

He was looking at obfuscated code, so some variables may have different names in your real code.

The construction itself should look something like this: 
(moved each parameter to a new line for clarity)

var url = "http://flights.lonelyplanet.com/flights?" 
  + "home_country=" + this.autocomplete.countryCode
  + "&currency=" + this.$currency.val()
  + "#/result?"
  + "outbounddate=" + outboundDate
  + "&inbounddate=" + inboundDate
  + "&origindlace=" + (this.$fromAirport.val() || this.$fromCity.val()) 
  + "&destinationplace=" + (this.$toAirport.val() || this.$toCity.val())
  + "&adults=" + e(".js-adult-num .js-select").val()
  + "&children=" + e(".js-child-num .js-select").val()
  + "&infants=" + e(".js-baby-num .js-select").val()

**Comment by laserchicken** [comment]
@lemmiestone I want to understand that: flights.lonelyplanet.com is skyscanner partner page, they are using our flight widget from rizzo and they will update it as soon as we let them know we changed it; is this correct?

**Comment by lemmiestone** [comment]
Sorry this wasn't clear.  The widget that needs to be updated is at http://www.lonelyplanet.com/flights

My understanding is that this needs to pass data to http://flights.lonelyplanet.com/ which is their page.

**Comment by laserchicken** [comment]
Url generation is ready but I noticed date picker works weird: you choose 16th and it sets 15th in query string. Is this correct behaviour or should I change it? @leejones

**Comment by lemmiestone** [comment]
This does not seem like correct behavior.  @jcreamer898 ?

**Comment by laserchicken** [comment]
I've already changed it. Someone was using `toISOString` to format dates, but it also converts to UTC, we don't want this, right? For me it was: 
date picker selected date - `Wed Mar 16 2016 00:00:00 GMT+0100 (CET)`
formated date - `2016-03-15` (`2016-03-15T23:00:00.000Z` exactly, two hours earlier in UTC, different date in fact).

**Comment by laserchicken** [comment]
Next thing I noticed is when you select start date in next month, return date is not updated automatically.
To reproduce: select start date in April, return date is still in March, when you submit skyscanner will display notification "your date was in the past..." and ask you to fill out a form again. I'm not sure if it's critical, maybe I should deploy today's changes first @lemmiestone ?

**Comment by lemmiestone** [comment]
I would go ahead and make this fix and deploy everything at once.

**Comment by laserchicken** [comment]
Fixed widget deployed on http://www.lonelyplanet.com/flights, I think we can close the issue. @lemmiestone

**Comment by lemmiestone** [comment]
This is looking good on my end. I will close.

**Comment by lemmiestone** [comment]
@laserchicken there are a couple of widgets on the essential information pages that are not passing information into flights.lonelyplanet.com.  You can see an example of this at the link below.  I also included a screenshot of the various links that push data to flights.lonelyplanet.com

http://www.lonelyplanet.com/france/essential-information

![essensial-information](https://cloud.githubusercontent.com/assets/556150/13817490/5f72b3f6-eb60-11e5-880e-1136d3a9d474.png)

**Comment by laserchicken** [comment]
right, I didn't know that, I'm on it @lemmiestone

**Comment by lemmiestone** [comment]
I didn't either..  thanks!

**Comment by laserchicken** [comment]
@lemmiestone that should be fixed now, please check

**Comment by laserchicken** [comment]
Next thing I noticed is minimal price, it doesn't seem to be working properly:
![screen shot 2016-03-22 at 18 00 08](https://cloud.githubusercontent.com/assets/5850443/13960419/93dc8084-f058-11e5-9c0b-6d05e995c5c9.png)
![screen shot 2016-03-22 at 18 00 00](https://cloud.githubusercontent.com/assets/5850443/13960420/93de0f1c-f058-11e5-83ec-375ddc6487e2.png)
When I click on it skyscanner shows me:
![screen shot 2016-03-22 at 18 05 45](https://cloud.githubusercontent.com/assets/5850443/13960459/bb83aaea-f058-11e5-814a-b9fb1c633c95.png)
So the cheapest price is 25 not 14 GBP. There is a lot of legacy code in need-to-know, it's quite messy, but if you want I can try to improve/fix it when I have some time between other tasks.

**Comment by lemmiestone** [comment]
@laserchicken we should get the prices right.  I don't want users to see a lower price and when they go to book it's higher.

**Comment by laserchicken** [comment]
ok, will do

**Comment by laserchicken** [comment]
@lemmiestone Things are more complicated than I initially thought. We are querying `browsequotes` api endpoint to get the cheapest price for the whole year from now. Take a look at their documentation https://github.com/Skyscanner/api-documentation/tree/master/browse_quotes#definition-of-browse-prices, it says `The browse API is not (...) Guaranteed to be accurate`.
I tested it with `curl` and I can confirm that endpoint returns inaccurate results (22$ instead of 24$ in case of London Stansted-La Rochelle query). Also, they explain how it works in `Messaging requirements` paragraph on http://business.skyscanner.net/portal/en-GB/Documentation/FlightsBrowseCacheOverview.
Quotes returned by `browsequotes` endpoint come from cache of user activity and may be out of date, so they suggest to add 'estimated' word next to displayed lowest price. This seems really weird to me, but it explains the problem we have. Anyway, I'm still investigating, maybe we could find a workaround.

**Comment by lemmiestone** [comment]
If it's a limitation on their api I wouldn't spend a ton of time on it then.  If we need to add estimated on the front-end we can.  If everything else is working I think we can close the ticket.

**Comment by laserchicken** [comment]
right, I would close it then
