### ISSUE TITLE
Pre-pop From and TO fields in flights widget

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1500]
I've been told this use to work.

The FROM and TO fields of the flights widget needs to be pre-populated

From is based on IP sniffing - airport nearby
TO is the destination of the page you are on

The widget is at.. 
http://www.lonelyplanet.com/france/transport/getting-around/flights

**Comment by laserchicken** [comment]
@lemmiestone It seems skyscanner finally fixed that (see. latest Neal Gilliland email). I tested for Floris ip and it works. Can be closed.
