### ISSUE TITLE
Create A/B Test for hotels

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1501]
We would like to setup an A/B test on our hotels experience.  Currently a user gets to our hotel detail view and they click "Check Availability" which displays the rooms that are available.  This allows them to click "Book" which takes them to booking.com.

We would like to test taking the user directly to the hotel detail view on booking.com when they click  "Check Availability" on our hotel detail view.  This would need to pass all their search criteria (Check In, Check Out, number of guest, and currency).

We want to do a 50% split.  Users should see the same alternative when (re)visiting the site.

We can use hotels.lonelyplanet.com for the test.

**Comment by lemmiestone** [comment]
We will need to get approval before going live.

**Comment by jcreamer898** [comment]
@lemmiestone you can actually put this in https://github.com/lonelyplanet/hotels.

Also, as a part of this we should probably default our form fields to a date so that we get better pricing data. Right now we've found that our rates are a ton higher when no dates are selected.

**Comment by lemmiestone** [comment]
Cool I will move it. The form fields will have a date.

**Comment by lemmiestone** [comment]
This issue was moved to lonelyplanet/hotels#129
