### ISSUE TITLE
Show more is throwing a 404 on sights

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1502]
Steps to recreate...

• Go to any Destination
• Go to Sights pageScroll to end of listed sights • • Click 'Show More'

It attempts to load and then gives  404 in console

**Comment by laserchicken** [comment]
This is example request url: http://www.lonelyplanet.com/caribbean/sights.json?page=2
@mkunkel I guess it fails because of https://github.com/lonelyplanet/dispatch/commit/b0327005bb977f0be924a36ae4c9b71fdda6dbdf
Do you think I could add `- "%.*/sights.json"`? That should fix the problem, right?

**Comment by jcreamer898** [comment]
@laserchicken seems legit, think you can get that fix in?

**Comment by laserchicken** [comment]
@jcreamer898 should I add $ anchor at the end or leave it as it is, I'm not sure...

**Comment by laserchicken** [comment]
@lemmiestone this is fixed, you can close the issue
