### ISSUE TITLE
Change G Adventures tracking

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1509]
We need to make a change to the tracking for G Adventures i.e. 

CURRENT 

www.example.com/?aff=18424&phone_code=LonelyPlanet 

NEW 
www.example.com/&?aff=18424&utm_source=lonelyplanet&utm_medium=referral&utm_campaign=lonelyplanet&phonecode=LonelyPlanet

**Comment by lemmiestone** [comment]
Got to.. 
https://www.lonelyplanet.com/germany/tours/history-culture/explore-central-europe


if you click on 'check prices and availability' it will then we will push you to G Adventures
 
Compare the tracking code now when getting pushed to G Adventures versus what it should be.

It needs to be on all pages for G Adventures

**Comment by laserchicken** [comment]
@lemmiestone are you sure I should change `phone_code` to `phonecode`?

**Comment by lemmiestone** [comment]
I'm going to guess that's a typo but I will need to confirm with Floris

**Comment by laserchicken** [comment]
done
