### ISSUE TITLE
Change 'Gay & Lesbian travellers' to 'LGBT travellers'

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1510]
On Essential Information pages 

Change 'Gay & Lesbian travellers' to 'LGBT travellers'

Example - http://www.lonelyplanet.com/usa/new-york-city/essential-information

**Comment by laserchicken** [comment]
you mean only this link:
![screen shot 2016-04-22 at 14 30 13](https://cloud.githubusercontent.com/assets/5850443/14741487/ca9087b4-0896-11e6-8bee-0870f8c13e51.png)
'Gay & Lesbian travel' to 'LGBT travellers', right? @lemmiestone

**Comment by lemmiestone** [comment]
Yes I believe that is what they are referring to.

**Comment by laserchicken** [comment]
@lemmiestone done, can be closed
