### ISSUE TITLE
Update i to i link in work and study section on Essential Information pages

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1512]
Essential Information pages that have a work and study section have a link download a free e-book.  The link to this needs to be updated.  The correct link is http://www.i-to-i.com/lonely-planet.html?utm_source=lonelyplanet&utm_medium=oa&utm_campaign=lonelyplanetgeneric_text

You can see an example of this at http://www.lonelyplanet.com/france/work-and-study

Also update copy:
CURRENT 
If you’d like to spend more time in Africa than a vacation allows, experiencing what it’s like to live and make a difference to the community in this amazing country,  

NEW 
If you’d like to spend more time in Africa than a vacation allows, experiencing what it’s like to live and make a difference to the local community,

**Comment by laserchicken** [comment]
@lemmiestone done
