### ISSUE TITLE
Syntax sugar & pattern

### ISSUE THREAD

**Issue by borisrorsvort** [lonelyplanet/rizzo#1513]
Hi, we started using the same component pattern used here but we were wonering if there would be a better way to write the props in haml code.

![screen shot 2016-04-21 at 6 05 29 pm](https://cloud.githubusercontent.com/assets/39081/14716208/350eb224-07ec-11e6-873c-1a0125d6834f.png)

Take this example. Some times they are many component like this and your haml start to be crowded with ruby props hashes all around which kind of defeat the purpose of the view clarity.

You could put them in helpers put thats not very encapsulated. Or presenters but they are not necessarily tied to an object.

Can I ask how you did this in the lonely planet app?

**Comment by jcreamer898** [comment]
Most of our applications use some kind of presenter to build the objects needed. Occasionally we have inline ruby in the templates, but we (obviously) avoid doing that as much as possible.

**Comment by borisrorsvort** [comment]
What if the component has no dynamic content? Do you still use a presenter?Do you have an example you can show or an article about this?

**Comment by jcreamer898** [comment]
We have a haml component that renders other components... 

https://github.com/lonelyplanet/rizzo/blob/3b32170b217420d52ea83cd79b35fd25808d9153/app/views/layouts/examples/core.html.haml#L6

**Comment by borisrorsvort** [comment]
Ok for the style guide you can have configs in yaml files but where do keep real app component config hash? I understand using presenters when its decorating a specific object, but take the above example, this doesnt make sense in an object presenter i think. So what would be the best option here? 
Could use the controller helper for that but it doesnt feels right either imho.

Do you have other suggestions?

**Comment by borisrorsvort** [comment]
@jcreamer898 did you have time to think about that?
