### ISSUE TITLE
Map functionality is broken

### ISSUE THREAD

**Issue by lemmiestone** [lonelyplanet/rizzo#1514]
If you hover your cursor over the map and then try enlarging it using the opposite-facing arrows, it doesn't work. However, If you don't hover over it, you can then click on the arrows to enlarge it - but you're then stuck with the enlarged map and can't reduce it back again.

**Comment by laserchicken** [comment]
@lemmiestone Which map do you mean? Could you give me example url?

**Comment by lemmiestone** [comment]
Sorry I meant to include one.  It's the maps on the POI pages.  http://www.lonelyplanet.com/usa/nashville/sights/architecture/ryman-auditorium

**Comment by laserchicken** [comment]
it's fixed @lemmiestone
