### ISSUE TITLE
Optimize Shop subnav

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo#1545]
from Gerard (floris cc'd):

The solution whereby the SHOP text links to shop homepage and the small quantity dot links to cart is not ideal - it is still confusing for customers because those two links are so close visually. I have also done some user tests internally to back this up too. 

Brad's (more complicated) solution: when there are contents in the cart, both the shop text and the red dot throw to cart. And where there are no contents in cart, the SHOP text throws to Shop homepage.

Jonathan's (less complicated) solution: make the notification thingy larger and more obvious or something. Only because of how our navigation works, we'll have to change the link after the page loads with JavaScript. 

Final Decision: Gerard is asking to throw both links to cart when there are contents (vs making the notification clearer).

is this possible?

**Comment by chrissysievers** [comment]
@thomasthesecond take a look at this and tell me if it needs to wait for Jonathan.

**Comment by thomasthesecond** [comment]
I should be able to do this @chrissysievers. Has a solution been decided on?

**Comment by chrissysievers** [comment]
@thomasthesecond Gerard is asking to throw both links to cart when there are contents (vs making the notification clearer). 

also, sorry for the hold up, i never got your notification above..so I'll check my settings out. Let me know if I'm holding anything else up for you.

**Comment by chrissysievers** [comment]
can you let me know an ETA @thomasthesecond ?
