### ISSUE TITLE
Lightbox z-index is below nav

### ISSUE THREAD

**Issue by WunderBart** [lonelyplanet/rizzo#1595]
Error cause: https://github.com/lonelyplanet/rizzo/pull/1593

![image](https://cloud.githubusercontent.com/assets/1451471/24370908/60d9eb1e-1329-11e7-9a2b-c104ecc28524.png)

/cc @thomasthesecond (just wanted to open issue as a reminder)

**Comment by thomasthesecond** [comment]
Caused by https://github.com/lonelyplanet/rizzo/pull/1593

**Comment by WunderBart** [comment]
@thomasthesecond any progress on this one?

**Comment by chrissysievers** [comment]
@WunderBart I'm meeting with Will today to replan our current sprint, so I should have some info over to you soon on when this can be tackled..sorry for the wait.

cc: @thomasthesecond

**Comment by thomasthesecond** [comment]
> You can open it via `Cmd+K` on any page @ http://rizzo.lonelyplanet.com/

**Comment by chrissysievers** [comment]
@WunderBart is this blocking you at all and what's the impact to you or the user? Checking this out and it looks like an internal only page that won't affect a user, so hoping we can formally plan this into the 4/24 sprint.

**Comment by WunderBart** [comment]
@chrissysievers this is not blocking me but it's a publicly visible bug on http://rizzo.lonelyplanet.com/ (it's not internal)

**Comment by chrissysievers** [comment]
@WunderBart Got it. Since it's not directly revenue-impacting, we'll pull it into our 4/24 - 5/12 sprint. Sorry for the wait..but we'll get to it.
