### ISSUE TITLE
Add Tourism Solutions to the Global Footer

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo#1616]
Tourism Solutions needs to be added to the global footer. 

- Placement should be between Press/Trade/Advertising and Terms and Conditions 
- Live url: http://www.lonelyplanet.com/tourism

**Comment by chrissysievers** [comment]
@bpotterbaum I wanted to give you an FYI / heads up that we're adding Tourism Solutions to the footer..no need to do anything.

**Comment by laserchicken** [comment]
This will break the layout (footer has fixed width 1000px):
![screen shot 2017-07-20 at 15 10 22](https://user-images.githubusercontent.com/5850443/28418971-f081d572-6d5d-11e7-8fde-307f83971fcd.png)

Maybe we could ask graphic designer to take a look? @chrissysievers

**Comment by chrissysievers** [comment]
@craig-murray we are being asked to add Tourism Solutions to the footer of lp.com but it doesn't currently fit in the footer since it's got a fixed width of 1000px. Can this be moved over to a designer for help?

@laserchicken should be pinged when it's ready for dev.

**Comment by craig-murray** [comment]
Yep @chrissysievers . .. @andycarmstrong can take a swift pass at how this should lay out across breakpoints.

**Comment by andycarmstrong** [comment]
@laserchicken Can I see an example of how it breaks the footer?

**Comment by andycarmstrong** [comment]
@chrissysievers @laserchicken 

If we modify the language, we can have it all fit within the 1000px container:

![screen shot 2017-07-25 at 10 03 10 am](https://user-images.githubusercontent.com/17987798/28578895-ab22761e-7120-11e7-89c2-f312dc186b0b.png)

About / Careers / Contact / Press, trade & advertising / Terms / Privacy policy / Tourism solutions

**Comment by laserchicken** [comment]
sorry for the confusion @andycarmstrong I was talking about old rizzo footer, you can see the example on http://www.lonelyplanet.com/newsletter

**Comment by andycarmstrong** [comment]
@laserchicken 

Well, then you remove all of the social icons but Facebook, Twitter, and Pinterest. Still, follow the new language updates and add your new link. That should do the trick!

**Comment by laserchicken** [comment]
ok, will do, thanks!

**Comment by chrissysievers** [comment]
@laserchicken just following up on this one? Would this go live with the global header updates that have been getting pushed?

I also know you've been out sick Mateusz, so take your time responding.

**Comment by laserchicken** [comment]
If it's not super urgent I would wait until we release 1% profile - I'm trying to avoid possible rollbacks etc. @chrissysievers

**Comment by chrissysievers** [comment]
Whatever is the most efficient, is good with me! I will let the TS team know. Thanks.

**Comment by laserchicken** [comment]
all pages updated
