### ISSUE TITLE
Best in Asia & /newsletter generating incorrect Regions

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo#1619]
The Best in Asia Sign up forms / modals are assigning Canada records incorrectly to the APAC instead of the AMERICAS region. These forms use the same set up as the newsletter sign from '/newsletter'. 

https://www.lonelyplanet.com/best-in-asia#competition

**Comment by nickfranciosi** [comment]
@chrissysievers can I get a bit a more info on this one. I feel like we talked about it some point and maybe even someone else was working on it. Not sure. Let me know if we have more info, cause I don't even see a form on that best in asia page. Thanks!

**Comment by chrissysievers** [comment]
I have no additional info on this, as it came from Thomas Duffy (who no longer works at LP.) I'm not sure, but this might be related to the salesforce rollout that happened sitewide that @katelynp43 and @robuye were involved with. 

It sounds like the core problem is likely with /newsletter and where he's seeing signups were with Best in Asia that is utilizing that form. 

I'd pause on this and hope that Katelyn or Rob can provide more context.

**Comment by robuye** [comment]
I can handle that, I'm working on Gonzo/Salesforce now.

**Comment by robuye** [comment]
This has been fixed, Canada belongs to AMERICAS now.

**Comment by chrissysievers** [comment]
Thanks. I asked Seb to let Caroline know when she returns later this month. She can let us know if it's not performing the way she expected, so I'd call this one done for now.
