### ISSUE TITLE
Update LP favicon

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo#1635]
Lonely Planet's favicon is the older logo, it should reflect the current one, found here: https://company-98919.frontify.com/d/zA3SDMNUX4s8/style-guide#/basics/logo.

Per Andy, use the favicon found here: [lp_favicon.ico.zip](https://github.com/lonelyplanet/rizzo/files/1391335/lp_favicon.ico.zip)

**Comment by jcreamer898** [comment]
A bit confused here, I don't think that the ENTIRE LP Logo is going to fit inside a Favicon...

**Comment by jcreamer898** [comment]
I think we need an actual designed Favicon, here's the issue, you can't just squish our logo down to Favicon size...

This is what it would look like...

![](http://d.pr/i/1n1QSH+)

**Comment by jcreamer898** [comment]
Which looks pretty awful by comparison... 

![](http://d.pr/i/04AcYQ+)

**Comment by jcreamer898** [comment]
@chrissysievers ^^

**Comment by chrissysievers** [comment]
@andycarmstrong I know you were once working on a style guide for .com...were any alt logos developed? Specifically favicons? Check out the issue above and the hurdles JC is running into. We need some UX advice.

**Comment by andycarmstrong** [comment]
@jcreamer898 @chrissysievers I recreated one for the Korean website a few months ago. Try this out:

[lp_favicon.ico.zip](https://github.com/lonelyplanet/rizzo/files/1391335/lp_favicon.ico.zip)

**Comment by chrissysievers** [comment]
@WunderBart is this one that you could try out?

**Comment by WunderBart** [comment]
Sure! Lemme take care of it.

**Comment by chrissysievers** [comment]
@andycarmstrong the favicon is looking pretty cramped. The devs will go ahead and push this live, but they flagged some concerns about it's readability. 

Does LP have any kind of logomark? (or is the old "lp" favicon it?)

![screen shot 2017-11-27 at 17 49 46](https://user-images.githubusercontent.com/20303852/33281606-748e38d8-d36b-11e7-8698-8a0bb58db9cb.png)

**Comment by chrissysievers** [comment]
@WunderBart I spoke with @andycarmstrong and @bpotterbaum this morning. They agree the full logo isn't good, but apparently the alternative "lp" favicon we currently use has already been discussed and not approved by the brand team. Because of that we _technically_ need to move forward with updating this to the full logo and the UX team should have more discussions with the Brand team on updating this: https://company-98919.frontify.com/d/zA3SDMNUX4s8/style-guide#/basics/logo to include a better favicon.

cc: @laserchicken
