### ISSUE TITLE
Italian Partner Site in footer results in error

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo#1640]
**Short Description of Bug**
HTTPS links via the language menu at the bottom of the screen are bringing up net cert errors.

**Steps I should follow to reproduce**
go to https://www.lonelyplanet.com/ scroll to the language options at the bottom, choose Italiano. 

New info, this also happens to:
-India
-Italy
-Russia
-Brazil
-Czech

**What are the results you expect?**
NET::ERR_CERT_AUTHORITY_INVALID error

**Additional Info**
I spoke to Mike K about this, wondering if it had to do with the recent https transition. Apparently, this this link is not specifying https. 

![pasted image at 2017_10_24 04_13 pm](https://user-images.githubusercontent.com/20303852/31968992-9711d25a-b8d8-11e7-8698-feb5eabc5efb.png)

He suggested a front end see if there is a script redireting to ```https://{selected_value}```

Link to original [Bug Report](https://trello.com/c/YtHfQzek/405-https-links-via-the-language-menu-at-the-bottom-of-the-screen-are-bringing-up-net-cert-errors).

**Comment by chrissysievers** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [HTTPS links via the language menu at the bottom of the screen are bringing up net cert errors.](https://trello.com/c/YtHfQzek/405-https-links-via-the-language-menu-at-the-bottom-of-the-screen-are-bringing-up-net-cert-errors)

**Comment by laserchicken** [comment]
re "see if there is a script redireting to https://{selected_value}": yes, I can confirm this:  https://github.com/lonelyplanet/rizzo-next/blob/c554c38985de44b9afb828dd624dc7dcc58d1e83/src/components/footer/footer_component.js#L14

**Comment by laserchicken** [comment]
re "wondering if it had to do with the recent https transition": yes, it's related (https://github.com/lonelyplanet/rizzo-next/commit/044e9464aa7bbd4c509e99ad7cfe31cb313db252)

**Comment by laserchicken** [comment]
I can just change that redirect back to `http` and test - it should work I believe.

**Comment by chrissysievers** [comment]
hey @laserchicken more info just came in on this one (I'll adjust the original issue above). Looks like more than Italian site is affected, and I didn't catch it..that's my mistake.

The Germans and French site have an https version that's working just fine, but these are also throwing errors:

-India - Seb to reach out to Indian
-Italy - International Licensing Team to manage
-Russia - International Licensing Team to manage
-Brazil (Portuguese) - International Licensing Team to manage
-Czech - International Licensing Team to manage

If you change the redirect back to http, would there be any negative consequences if and when these sites transition over to https?

Secondly, @mkunkel, Seb said that in this context and timeframe SEO hit would be minimal. So no worries there. And we will work to get the others up to https (as much as we can).

**Comment by laserchicken** [comment]
I don't think there will be any negative consequence - if they transition they should just force https by redirecting http->https. @chrissysievers

**Comment by laserchicken** [comment]
Do you want me to update it @chrissysievers?

**Comment by chrissysievers** [comment]
Yes, please.
