### ISSUE TITLE
Avatar cropped incorrectly in Thorntree

### ISSUE THREAD

**Issue by chrissysievers** [lonelyplanet/rizzo#1642]
_From @chrissysievers on October 26, 2017 13:12_

When in Thorntree, users' profile pic in the header is showing inconsistent / strange cropping. This seems to have happened when BiT was added to the global header.

To recreate:
1. log into your profile.
2. go to https://www.lonelyplanet.com/thorntree/dashboard

<img width="504" alt="screen shot 2017-10-26 at 8 10 50 am" src="https://user-images.githubusercontent.com/20303852/32054812-4b6eb374-ba25-11e7-9f61-5d38bdbdd3bb.png">

_Copied from original issue: lonelyplanet/dotcom-profile#421_

**Comment by nidalaa** [comment]
Also in https://www.lonelyplanet.com/hotels, so it means that last changes in rizzo-next do not go well with rizzo.

cc @WunderBart @laserchicken

**Comment by nickfranciosi** [comment]
this is actually just a css issue, not cropping - @laserchicken and I are looking at the best place to put the css to force this to display properly

**Comment by WunderBart** [comment]
This is caused by different user agent styles. Probably we use different normalize/reset.css sheets. For now it would be safest to just force `border: none` & `padding: 0` in `rizzo-next`'s `.avatar` class.

**Comment by laserchicken** [comment]
All legacy apps updated - should be good now.
